"""added models

Revision ID: b41221689141
Revises: aae10ce3a5d3
Create Date: 2024-02-17 14:01:21.429481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41221689141'
down_revision = 'aae10ce3a5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosage_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_dosage_histories_prescription_id_prescriptions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dosage_histories_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prescription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_side_effects_prescription_id_prescriptions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_side_effects_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('side_effects')
    op.drop_table('dosage_histories')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
